### ISSUE TITLE
ImportError: Wake Word marvin with module ovos-ww-plugin-precise-lite failed to load

### ISSUE THREAD

**Issue by mikejgray** [OpenVoiceOS/ovos-plugin-manager#166]
When trying to use ovos-ww-plugin-precise-lite on Neon, the following error occurs:

```python
2023-06-08 19:05:54.157 - voice - ovos_plugin_manager.wakewords:create_hotword:197 - ERROR - Wake Word marvin with module ovos-ww-plugin-precise-lite failed to load
Traceback (most recent call last):
  File "/home/neon/venv/lib/python3.7/site-packages/ovos_plugin_manager/wakewords.py", line 194, in create_hotword
    return cls.load_module(module, hotword, ww_config, lang, loop)
  File "/home/neon/venv/lib/python3.7/site-packages/ovos_plugin_manager/wakewords.py", line 170, in load_module
    raise ImportError(f'Wake Word {hotword} with module {module} '
ImportError: Wake Word marvin with module ovos-ww-plugin-precise-lite failed to load
2023-06-08 19:05:54.160 - voice - ovos_dinkum_listener.voice_loop.hotwords:load_hotword_engines:180 - ERROR - Failed to load hotword: marvin
```

Same error with other tflite models (I also tested hey_mycroft).

I think it's coming from [here](https://github.com/OpenVoiceOS/ovos-plugin-manager/blob/dev/ovos_plugin_manager/wakewords.py#L196).

```bash
(venv) neon@neon:~$ pip list | grep ovos-plugin-manager
ovos-plugin-manager                     0.0.23
```

It doesn't seem to be an issue in OVOS, so that leads me to think maybe there's a mismatch with Python 3.7, but it seems unlikely because the test suite here checks 3.7.

**Comment by JarbasAl** [comment]
did you install either tensorflow or tflite_runtime ?

those need to be installed manually,  `ImportError: Wake Word marvin with module ovos-ww-plugin-precise-lite failed to load` means the class was never loaded from the plugin, so i'm guessing it failed to get tflite intreperter

**Comment by mikejgray** [comment]
🤦🏼‍♂️ 
@NeonDaniel Looks like I found the issue...

**Comment by mikejgray** [comment]
https://github.com/NeonGeckoCom/NeonCore/pull/469
