### ISSUE TITLE
Error about Azure TTS plugin

### ISSUE THREAD

**Issue by timonvanhasselt** [OpenVoiceOS/ovos-plugin-manager#193]
I think the mapping is missing for the [Azure TTS plugin](https://github.com/OpenVoiceOS/ovos-tts-plugin-azure) in the plug-in manager. BTW:  the voice is working, regardless of the following error.

```
2023-10-30 12:57:59.175 - skills - ovos_plugin_manager.utils:load_plugin:155 - WARNING - Could not find the plugin PluginTypes.TTS.ovos-tts-plugin-azure
2023-10-30 12:57:59.184 - skills - ovos_plugin_manager.tts:create:216 - ERROR - The TTS plugin "ovos-tts-plugin-azure" could not be loaded.
Available modules: ovos-tts-plugin-dummy
Traceback (most recent call last):
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_plugin_manager/tts.py", line 212, in create
    raise RuntimeError(f"unknown plugin: {tts_module}")
RuntimeError: unknown plugin: ovos-tts-plugin-azure
2023-10-30 12:57:59.186 - skills - ovos_audio.service:__init__:93 - ERROR - unknown plugin: ovos-tts-plugin-azure
Traceback (most recent call last):
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_audio/service.py", line 90, in __init__
    self._maybe_reload_tts()
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_audio/service.py", line 318, in _maybe_reload_tts
    self.tts = TTSFactory.create(config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_audio/tts.py", line 9, in create
    return OVOSTTSFactory.create(config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_plugin_manager/tts.py", line 212, in create
    raise RuntimeError(f"unknown plugin: {tts_module}")
RuntimeError: unknown plugin: ovos-tts-plugin-azure
2023-10-30 12:57:59.187 - skills - ovos_audio.service:on_error:44 - ERROR - Audio service failed to launch (unknown plugin: ovos-tts-plugin-azure).
```

**Comment by timonvanhasselt** [comment]
I don't think I had the issue after this one again. So I close the issue.
